Config = {}

Config.Items = {
label = "Cold Store",
    slots = 23,
    items = {
        [1] = {
            name = "uwububbleteablueberry",
            price = 10,
            amount = 5,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "uwububbletearose",
            price = 10,
            amount = 5,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "uwububbleteamint",
            price = 10,
            amount = 5,
            info = {},
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "uwupancake",
            price = 10,
            amount = 5,
            info = {},
            type = "item",
            slot = 4,
        },
        [5] = {
            name = "uwucupcake",
            price = 10,
            amount = 5,
            info = {},
            type = "item",
            slot = 5,
        },
        [6] = {
            name = "uwuvanillasandy",
            price = 10,
            amount = 5,
            info = {},
            type = "item",
            slot = 6,
        },
        [7] = {
            name = "uwuchocsandy",
            price = 10,
            amount = 5,
            info = {},
            type = "item",
            slot = 7,
        },
        [8] = {
            name = "uwubudhabowl",
            price = 10,
            amount = 5,
            info = {},
            type = "item",
            slot = 8,
        },
        [9] = {
            name = "uwusushi",
            price = 10,
            amount = 5,
            info = {},
            type = "item",
            slot = 9,
        },
        [10] = {
            name = "uwumisosoup",
            price = 10,
            amount = 5,
            info = {},
            type = "item",
            slot = 10,
        },
        [11] = {
            name = "uwubentobox",
            price = 25,
            amount = 5,
            info = {},
            type = "item",
            slot = 11,
        },
        [12] = {
            name = "uwubbessence",
            price = 2,
            amount = 20,
            info = {},
            type = "item",
            slot = 12,
        },
        [13] = {
            name = "uwuroseessence",
            price = 2,
            amount = 20,
            info = {},
            type = "item",
            slot = 13,
        },
        [14] = {
            name = "uwumintessence",
            price = 2,
            amount = 20,
            info = {},
            type = "item",
            slot = 14,
        },
        [15] = {
            name = "egg",
            price = 2,
            amount = 20,
            info = {},
            type = "item",
            slot = 15,
        },
        [16] = {
            name = "flour",
            price = 2,
            amount = 20,
            info = {},
            type = "item",
            slot = 16,
        },
        [17] = {
            name = "milk",
            price = 2,
            amount = 20,
            info = {},
            type = "item",
            slot = 17,
        },
        [18] = {
            name = "misopaste",
            price = 2,
            amount = 20,
            info = {},
            type = "item",
            slot = 18,
        },
        [19] = {
            name = "tapiokaballs",
            price = 2,
            amount = 20,
            info = {},
            type = "item",
            slot = 19,
        },
        [20] = {
            name = "tea",
            price = 2,
            amount = 20,
            info = {},
            type = "item",
            slot = 20,
        },
        [21] = {
            name = "tofu",
            price = 2,
            amount = 20,
            info = {},
            type = "item",
            slot = 21,
        },
        [22] = {
            name = "water_bottle",
            price = 2,
            amount = 20,
            info = {},
            type = "item",
            slot = 22,
        },
        [23] = {
            name = "rawsugar",
            price = 2,
            amount = 20,
            info = {},
            type = "item",
            slot = 23,
        },
        [24] = {
            name = "tuna",
            price = 2,
            amount = 1,
            info = {},
            type = "item",
            slot = 24,
        },
        [25] = {
            name = "rice",
            price = 2,
            amount = 20,
            info = {},
            type = "item",
            slot = 25,
        },
        [26] = {
            name = "avocado",
            price = 2,
            amount = 20,
            info = {},
            type = "item",
            slot = 26,
        },
        [27] = {
            name = "chocolate",
            price = 5,
            amount = 20,
            info = {},
            type = "item",
            slot = 27,
        },
        [28] = {
            name = "vanillabean",
            price = 2,
            amount = 20,
            info = {},
            type = "item",
            slot = 28,
        },
        [29] = {
            name = "nori",
            price = 2,
            amount = 20,
            info = {},
            type = "item",
            slot = 29,
        },
        [30] = {
            name = "umami",
            price = 2,
            amount = 20,
            info = {},
            type = "item",
            slot = 30,
        },
        [31] = {
            name = "mixedlettuce",
            price = 2,
            amount = 20,
            info = {},
            type = "item",
            slot = 31,
        },
        [32] = {
            name = "mango",
            price = 2,
            amount = 20,
            info = {},
            type = "item",
            slot = 32,
        },
    }
}